apiVersion: apps/v1
kind: Deployment
metadata:
  name: raja-deployment
spec:
  selector:
    matchLabels:
      app: raja
  replicas: 2
  template:
    metadata:
      labels:
        app: raja
    spec:
      containers:
      - name: raja
        image: rajatherise/covid:latest
        ports:
        - containerPort: 80

